"""Rebuild the LOCAL auth_config.yaml. One command, no editing.

    python restore_auth_config.py

WHY THIS EXISTS
---------------
app/auth_config.yaml is gitignored on purpose — real credentials never
belong in git, even a private repo. That also means a `git clean -X`
deletes it and git cannot bring it back.

It was deleted on 2026-08-14 by `git clean -fXd -e app/data -e
app/auth_config.yaml`, which was supposed to protect both paths and did
the opposite. **-e ADDS an exclude pattern, and under -X a file that is
"more ignored" is MORE likely to be removed, not less.** The flag means
the reverse of what it reads like. Never run git clean in this repo; the
find/rm commands for __pycache__ do the whole job and cannot touch
anything but caches.

WHAT IT DOES NOT AFFECT
-----------------------
The LIVE SITE. Render mounts its own copy through Secret Files at deploy
time, exactly as auth_config.example.yaml instructs. Subscribers were
never logged out. This only restores the local Codespace copy so the app
runs when you preview it there.

SECRETS ARE GENERATED HERE, NOT COPIED
--------------------------------------
The cookie key is a fresh secrets.token_hex(32) every run. That is not
tidiness: on 2026-08-05 the live config was found carrying the SAME
cookie key as the committed template, copied across and never rotated.
That key signs the session cookie — anyone holding it can forge a
session for any username and role, admin included, without a password.
This script cannot reproduce that mistake because it never has a
default to copy.

Passwords are typed at the prompt, hashed through the same
streamlit_authenticator hasher the app verifies with, and the plaintext
is never written anywhere.
"""
import getpass
import os
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "app" / "auth_config.yaml"


def _hash(plain):
    import streamlit_authenticator as stauth
    return stauth.Hasher.hash(plain)


def _ask(prompt, default=""):
    got = input(f"{prompt}{f' [{default}]' if default else ''}: ").strip()
    return got or default


def main() -> int:
    if OUT.exists():
        print(f"{OUT} already exists.")
        print("Delete it first if you really mean to rebuild it — this "
              "script will not overwrite credentials that are already "
              "working.")
        return 1

    print("Rebuilding app/auth_config.yaml. Nothing is written until the "
          "end, and no plaintext password is stored.\n")

    users = []
    # The admin account is not optional: is_admin() gates the Calibration
    # and Debug Roster pages, and a config with no admin locks you out of
    # the tooling you use to check the record.
    print("--- admin account (unlocks Calibration and Debug Roster) ---")
    a_user = _ask("username", "admin")
    a_name = _ask("display name", "Admin")
    a_mail = _ask("email", "admin@loscappers.com")
    while True:
        p1 = getpass.getpass("password (typing is hidden): ")
        if len(p1) < 8:
            print("  at least 8 characters, please.")
            continue
        if p1 == getpass.getpass("repeat it: "):
            break
        print("  those did not match.")
    users.append((a_user, a_name, a_mail, _hash(p1), "admin"))

    print("\n--- subscriber accounts ---")
    print("Add as many as you like. Press Enter on the username to stop.")
    while True:
        u = _ask("username (Enter to finish)")
        if not u:
            break
        n = _ask("  display name", u)
        e = _ask("  email", f"{u}@loscappers.com")
        while True:
            p1 = getpass.getpass("  password (hidden): ")
            if len(p1) < 8:
                print("    at least 8 characters, please.")
                continue
            if p1 == getpass.getpass("  repeat it: "):
                break
            print("    those did not match.")
        users.append((u, n, e, _hash(p1), "subscriber"))

    body = ["# GENERATED by restore_auth_config.py — real credentials.",
            "# Gitignored on purpose. Never commit this file.",
            "#",
            "# The live site does NOT use this copy: Render mounts its own",
            "# through Secret Files. Changing a password here changes it",
            "# for local preview only.",
            "",
            "credentials:",
            "  usernames:"]
    for u, n, e, h, role in users:
        body += [f"    {u}:",
                 f"      email: {e}",
                 f"      name: {n}",
                 f"      password: {h}",
                 f"      role: {role}"]
    body += ["",
             "cookie:",
             "  name: los_cappers_auth",
             "  # Freshly generated. This key signs the session cookie —",
             "  # anyone holding it can forge a session for any user and",
             "  # role without a password. Never copy one between configs.",
             f"  key: {secrets.token_hex(32)}",
             "  expiry_days: 7",
             ""]

    OUT.write_text("\n".join(body), encoding="utf-8")
    os.chmod(OUT, 0o600)
    print(f"\nWrote {OUT} with {len(users)} user(s) and a fresh cookie key.")
    print("Nothing to commit — the file is gitignored, which is why it "
          "vanished and why that is correct.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
